- .gitattributes
+ Remove /src and /build.sh from .gitattributes
+ Ensure export-ignore added where missing
> .gitattributes fixes

- themes/nswds/templates/NSWDPC/Members/Includes/Directory.ss
- themes/nswds/templates/NSWDPC/Members/Includes/DirectoryMember.ss
- themes/nswds/templates/NSWDPC/Members/Includes/Links.ss
- themes/nswds/templates/NSWDPC/Members/Includes/MembersTable.ss
- themes/nswds/templates/NSWDPC/Members/Layout/MemberDirectoryController.ss
- themes/nswds/templates/NSWDPC/Members/Layout/MemberDirectoryController_view.ss
- themes/nswds/templates/NSWDPC/Members/MemberProfileDirectorySearchForm.ss
+ Add templates for directory support
> Directory templates

- themes/nswds/templates/NSWDPC/Members/Includes/BasicMemberProfile.ss
- themes/nswds/templates/NSWDPC/Members/Includes/GenericPage.ss
- themes/nswds/templates/NSWDPC/Members/Includes/LoggedOut.ss
- themes/nswds/templates/NSWDPC/Members/Includes/Me.ss
- themes/nswds/templates/NSWDPC/Members/Includes/Title.ss
+ New: loggedout template
+ New: basic member profile template
+ Update: handle external management content in templates
+ ENH: remove unnecessary CSS classes on title
> Update member profile templates

- README.md
- docs/en/001_index.md
- docs/en/002_integration.md
- docs/en/003_filter_form.md
- docs/en/100_branding.md
- docs/en/101_advanced_configuration.md
> v3 documentation update

- themes/nswds/templates/DNADesign/ElementalList/Model/ElementList.ss
- themes/nswds/templates/NSWDPC/Waratah/ElementalList/Includes/ListItems.ss
- themes/nswds/templates/NSWDPC/Waratah/Includes/PageSearchResults.ss
- themes/nswds/templates/nswds/Includes/ListItem.ss
+ Fixes for list item links not being passed through correctly.
+ Handle ContentLink, LinkTarget and no link
+ If no link, do not apply HTML
+ Fix: SubTitle -> Subtitle
+ Fix: listitems -> listitem
> List item link fixes and improvements

- themes/nswds/app/frontend/src/scss/components/waratah/_fixes.scss
+ Remove workaround CSS as issue was fixed in nsw-design-system (229)
> Remove calc() override used as workaround until fixed upstream

- themes/nswds/app/frontend/src/js/app.js
- themes/nswds/app/frontend/src/js/components/videoplayer.js
- themes/nswds/templates/NSWDPC/Waratah/Includes/IframeVideo.ss
+ Add video player in nsw-dialog handing via postMessage API and MutationObserver
> Video Player

- themes/nswds/app/frontend/src/scss/app.scss
- themes/nswds/app/frontend/src/scss/components/waratah/_scale.scss
+ Add `.wrth-scale-{$size} > *` utility class
> feat: add a scale utility class

- themes/nswds/app/frontend/src/scss/app.scss
- themes/nswds/app/frontend/src/scss/components/waratah/_feature.scss
- themes/nswds/templates/NSWDPC/Elemental/Models/ExtensibleSearch/ElementalExtensibleSimpleSearch.ss
- themes/nswds/templates/NSWDPC/Waratah/ElementDecoratedContent/Includes/Profile.ss
- themes/nswds/templates/NSWDPC/Waratah/ElementDecoratedContent/Includes/ProfileContent.ss
- themes/nswds/templates/NSWDPC/Waratah/ElementDecoratedContent/Includes/ProfileImage.ss
Adds a basic feature component
+ wrth-feature component CSS
+ Supports fields provided by ElementDecoratedContent
+ Provide a template for the 'profile' subtype of ElementDecoratedContent
+ Image alignment support (left / right)
+ default template to match 3-col grid
+ Optional Link target, linking to somewhere else
+ Provide basic search template
> Basic "feature" component

- src/Extensions/SiteConfigExtension.php
- src/Services/Analytics/AbstractAnalyticsService.php
- src/Services/Analytics/GA3.php
- src/Services/Analytics/GA4.php
- src/Services/Analytics/GTM.php
- src/Services/Analytics/GTMNonce.php
- themes/nswds/templates/NSWDPC/Waratah/Includes/GTMBody.ss
- themes/nswds/templates/NSWDPC/Waratah/Includes/GTMHead.ss
+ Split analytics implementations into service classes
+ Move scripts out of templates
+ Add nonce value support
> Analytics enhancements

- themes/nswds/app/frontend/src/scss/components/waratah/_video.scss
- themes/nswds/templates/NSWDPC/Elemental/Models/FeaturedVideo/GalleryVideo.ss
+ Use 16:9 gallery video thumbnail
+ Update placeholder to use CSS `aspect-ratio: 16/9`
+ Update ss embed layout to use `aspect-ratio: 16/9`, drop embed and object support
Ref: https://caniuse.com/mdn-css_properties_aspect-ratio
> Gallery video thumbnail improvements

- themes/nswds/app/frontend/src/scss/components/silverstripe/_mfa.scss
+ Override (remove) box-shadow button style introduced in silverstripe/mfa
+ Update spacing
> MFA button changes

- src/Extensions/DesignSystemAssetExtension.php
+ Bump jquery version + SRI hash.
+ Block previous version.
> jquery version update

- src/Extensions/ElementSectionNavigationExtension.php
- themes/nswds/templates/Dynamic/Elements/Section/Elements/ElementSectionNavigation.ss
+ implement section navigation in its own template
+ taking into account card style and columns
+ provide helper methods for template
+ Implement promo as horizontal card.
+ Use PageLastUpdated implementation for date display
> Section Navigation fixes and improvements

- _config/login-forms.yml
- src/Extensions/OAuthLoginFormExtension.php
+ Handle return type, avoid using deprecated property
+ Move configuration to own section
> login form extension improvements

- _config/forms.yml
- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
- themes/nswds/templates/SilverStripe/Forms/FileField.ss
- themes/nswds/templates/nswds/Includes/Loader.ss
- themes/nswds/templates/nswds/Includes/StatusLabel.ss
- update FileField template
- add Loader component template
- add StatusLabel component template
> Update to nsw-design-system 3.4.0

- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
+ Bump nsw-design-system to 3.6.0
Ref: https://github.com/digitalnsw/nsw-design-system/compare/v3.5.3...v3.6.0
> Bump nsw-design-system to 3.6.0

- themes/nswds/templates/NSWDPC/Waratah/Security/Includes/MainBody.ss
- themes/nswds/templates/Security.ss
+ Updates the Security template to handle instances where no `$Layout` is present.
> Template rendering update when no layout is present

- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
+ Update nsw-design-system to ^3.7.0
> nsw-design-system v3.7.0

- themes/nswds/templates/DNADesign/Elemental/Layout/ElementHolder_VirtualLinked.ss
Module sets this layout template in a recent version, this change provides support for that specific template.
> Add virtual linked template

- src/Extensions/DesignSystemAssetExtension.php
+ Modify test for whether requirements have been/should be applied
> Update requirements loading handling, modify test for whether requirements should be applied

- composer.json
+ Loosen requirements on boilerplate modules
> Update max version for requirements

- _config/extensions.yml
+  Remove config override, allow project to set.
> Use default framework settings for this value

- docs/en/003_filter_form.md
- src/Extensions/FilterFormExtension.php
- src/Services/FilterFormTrait.php
- src/Traits/FilterFormTrait.php
+ Fixes incorrect namespace for FilterFormTrait
+ Provide support where previous namespace is used.
> Fix: incorrect namespace FilterFormTrait

- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
+ [Update nsw-design-system 3.11.0](https://github.com/nswdpc/waratah/commit/4b1009308e37754ac99aad1db44253d3a162d4de)
> Update nsw-design-system 3.11.0

- themes/nswds/templates/SilverStripe/Forms/FileField.ss
- themes/nswds/templates/SilverStripe/UserForms/Model/EditableFormField/EditableFileField.ss
- themes/nswds/templates/nswds/Includes/FileUpload.ss
+ Ensure both FileField and EditableFileField use the same component template
> Fix: file upload template

- src/Extensions/DesignSystemAssetExtension.php
+ Remove requirements_loaded handling. This avoids issues when requirements are cleared
> Remove requirements_loaded handling

- themes/nswds/app/frontend/package-lock.json
+ Bring in fixes in nsw-design-system 3.11.1/2
> Update nswds to bring in multi-select fix

- themes/nswds/templates/NSWDPC/Elemental/Models/FeaturedVideo/GalleryVideo.ss
+ Use flush grid
+ Give 'Watch' button more space, provide padding similar to heading/title
+ Move Description/HTML value to full width section
> Improve gallery layout

- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
+ Update @babel devDependencies
> Update babel dev dependencies

- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
+ [Bump caniuse-lite](https://github.com/nswdpc/waratah/commit/1a1151167630aa20ed221a099992d9f2f1d5baf5)
+ [Bump nsw-design-system 3.12.0](https://github.com/nswdpc/waratah/commit/8d0c4f039e57c3b5c1ab6f2325ccefa1c9dd5128)
> Update nsw-design-system ^3.12

- themes/nswds/app/frontend/src/scss/components/waratah/_card.scss
+ Fix: ensure card content text contrasts with background colour
> Fix card content hover text colour

- themes/nswds/app/frontend/src/scss/components/waratah/_slider.scss
+ New: add new gallery view option + support inverted section
+ Improve consistency across gallery options
+ Bring `.no-image` selector within `.nsw-grid[data-gallery]`
> Gallery options/cleanup

- src/Extensions/FormFieldExtension.php
- themes/nswds/app/frontend/src/js/app.js
- themes/nswds/app/frontend/src/js/components/micromodal.js
- themes/nswds/app/frontend/src/js/components/sidenav.js
- themes/nswds/app/frontend/src/js/components/slimselect.js
- themes/nswds/app/frontend/src/js/components/videoplayer.js
- themes/nswds/templates/SilverStripe/Forms/ListboxField.ss
+ Modify the ListboxField to require opt-in to nswds multi-select component. To enable this, add an attribute `data-nsw-multiselect` to the specific field, which will add the `nsw-multi-select` wrapper to the field.
+ Modify component loading to catch errors on a per-component basis
> Update multiselect handling

- composer.json
- themes/nswds/templates/Page.ss
+ Bump version requirement
+ Remove unnecessary template include
> Update feedback assist requirement

- composer.json
- src/Extensions/SiteConfigExtension.php
- themes/nswds/templates/NSWDPC/Waratah/Includes/GTMBody.ss
- themes/nswds/templates/NSWDPC/Waratah/Includes/GTMHead.ss
Will resolve #91
Changes
+ Add module as requirement (4adf8f2368f3358fea64d4c4f6afc004fad585d2)
+ Remove newly duplicated code (4adf8f2368f3358fea64d4c4f6afc004fad585d2)
+ Update templates (6cebdcd592ae17917d534db19e119a7b6b00d1c1)
> Add analytics chooser

- themes/nswds/app/frontend/src/scss/app.scss
- themes/nswds/app/frontend/src/scss/components/waratah/_dl.scss
+ Add definition list `<dl>` styling
+ Stacks at sm viewport
> Definition list

- src/Models/DesignSystemConfiguration.php
+ Update button variants - add 'Brand Dark Outline Solid' and 'White Outline'
Ref #60
> Add button variants to ButtonStateSelectionField

- themes/nswds/templates/nswds/Includes/CloseButton.ss
- themes/nswds/templates/nswds/Includes/Icon.ss
+ Add Close button template, add Icon_Size option to Icon template.
Ref #61
```html
<% include nswds/CloseButton %>
<% include nswds/CloseButton CloseButton_Size=20 %>
<% include nswds/CloseButton CloseButton_Size=24 %>
<% include nswds/CloseButton CloseButton_Size=30 %>
<% include nswds/CloseButton CloseButton_Size=36 %>
```
> Add Close button template

- composer.json
- src/Services/Analytics/AbstractAnalyticsService.php
- src/Services/Analytics/GA3.php
- src/Services/Analytics/GA4.php
- src/Services/Analytics/GTM.php
- src/Services/Analytics/GTMNonce.php
+ Deprecate analytics service classes
+ Mark classes as not enabled, require minimum version of analytics chooser module
+ Update no longer required abstract class
> Deprecate Analytics service classes

- themes/nswds/app/frontend/package-lock.json
+ Update packages marked in npm audit
+ Update caniuse-lite
> Update npm / audit

- themes/nswds/templates/NSWDPC/Waratah/Includes/Results.ss
+ Add support for label to result list items
> PrimaryLabel support in Results template

- themes/nswds/templates/NSWDPC/Waratah/Includes/PageForm.ss
> Fix: use correct end tag in template

- themes/nswds/app/frontend/src/js/components/slimselect.js
- themes/nswds/app/frontend/src/scss/components/thirdparty/_slimselect.scss
+ set `ss-listbox` class on the element in JS
+ replace upstream 'display:none' with CSS that will make the element focusable during validation (required attribute)
> (slimselect) update the UI so that the element is focusable during validation

- themes/nswds/templates/NSWDPC/Waratah/Includes/GlobalAlert.ss
- themes/nswds/templates/Page.ss
+ Allow a project to override how global and page alerts are displayed, via two separate included templates
> Versatile alerts

- themes/nswds/templates/NSWDPC/Waratah/Includes/LastUpdated.ss
- themes/nswds/templates/NSWDPC/Waratah/Includes/PageContent.ss
- themes/nswds/templates/NSWDPC/Waratah/Includes/PageWrapper.ss
+ Fix: remove `nsw-layout__sidebar--desktop` class on right sidebar
+ Ensure last updated date on page appears below all content
> Fix remove sidebar desktop

- themes/nswds/app/frontend/src/scss/components/waratah/_list.scss
- themes/nswds/templates/NSWDPC/Elemental/Models/Taxonomy/ElementTaxonomyList.ss
+ Fix: remove extra end tag in template
+ Update styling to veritcally align icons with text
> Improve taxonomy list template

- composer.json
+ (chore) update composer meta to remove URL
> Update composer meta

- composer.json
- themes/nswds/templates/NSWDPC/Elemental/Models/Iframe/ElementIframe.ss
+ Add template fix for iframe polyfill
+ Ensure the minimum version is set to support `$HasPolyfill`
> Iframe polyfill update

- themes/nswds/templates/NSWDPC/Elemental/Models/Slider/ElementSlider.ss
- themes/nswds/templates/NSWDPC/Elemental/Models/Slider/Slide.ss
+ Migrate slider to carousel card component
+ Simplify markup
+ Use Slide.ss template
> Improve slider template

- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
- themes/nswds/templates/nswds/Includes/Footer.ss
+ Update nsw-design-system to 3.17.5
+ Add new class in footer for Acknowledgement of Country
> (nsw-design-system) update to 3.17.5, update class in footer

- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
+ Update nsw-design-system to 3.18.3
> Update nsw-design-system to 3.18.3

- themes/nswds/templates/NSWDPC/Waratah/Forms/Includes/Actions.ss
+ Add missing closing `div` tag in form actions
> Fix: add missing closing div

- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
+ Update nsw-design-system to 3.18.5, applies fixes listed in https://github.com/digitalnsw/nsw-design-system/compare/v3.18.4...v3.18.5
> Update nsw-design-system to 3.18.5

- docs/en/006_v2_changes.md
+ (doc) update changes documentation
> (doc) update changes documentation

- _config/userforms.yml
- src/Extensions/DesignSystemAssetExtension.php
- src/Extensions/UserDefinedFormControllerExtension.php
- src/Models/DesignSystemConfiguration.php
+ Conditional requirement of jQuery, default off
+ Bump supported version of jQuery
+ Add an extension for UserDefinedFormController to require the supported version of jQuery
> Configurable jQuery

- docs/en/005_extra_components.md
- themes/nswds/app/frontend/src/js/components/slimselect.js
- themes/nswds/app/frontend/src/scss/components/thirdparty/_slimselect.scss
+ Add support for 'addable' event to slimselect component
+ Update documentation
> Add support for 'addable' to slimselect component

- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
+ Update nsw-design-system to 3.18.6
> Update nsw-design-system to 3.18.6

- themes/nswds/templates/Bigfork/SilverStripeSimpleDateField/SimpleDateField.ss
- themes/nswds/templates/BreadcrumbsTemplate.ss
- themes/nswds/templates/SilverStripe/UserForms/Form/Includes/UserFormProgress.ss
+ Use IsFirst/IsLast over First/Last
+ Remove obsolete template
> Update deprecated use of First/Last

- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
- themes/nswds/templates/nswds/Includes/HeroSearch.ss
+ Update nsw-design-system to 3.18.7
+ Add support for HeroSearch image as img tag
> Update nsw-design-system to 3.18.7

- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
+ Update nsw-design-system to 3.18.8
> nsw-design-system 3.18.8

- themes/nswds/templates/Security.ss
+ Add relevant metadata to Security template
> Update meta tags in security template

- src/Models/ElementalUtilityList.php
+ Fixes a deprecation warning with a possibly null value
> Fix: deprecation

- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
- themes/nswds/templates/nswds/Includes/Breadcrumbs.ss
+ Update nsw-design-system to 3.19.0
See: https://github.com/digitalnsw/nsw-design-system/compare/v3.18.11...v3.19.0
Ref: #140
> Update nsw-design-system to 3.19.0

- _config/elemental.yml
+ Fix: remove reference to elemental block that is not shipped by default
> Fix: remove element from list of allowed ElementList elements

- themes/nswds/templates/nswds/Includes/FormFieldNotification.ss
+ Add the form field message value as provided to the template
> Handle form field message value as provided

- composer.json
- src/Forms/SectionSelectionField.php
+ Add helper scripts for development
> (dev) add dev helper scripts
