nswdpc/waratah

- docs/en/001_index.md
- src/Extensions/DesignSystemAssetExtension.php
- themes/nswds/app/frontend/src/scss/app.scss
- themes/nswds/app/frontend/src/scss/components/waratah/_mixins.scss
- themes/nswds/app/frontend/src/scss/components/waratah/_typography.scss
- themes/nswds/app/static/editor.css
Previously, projects were required to add Public Sans as a per-project customisation. This change sets up Public Sans from the start to override the Monserrat shipped as default in v2.14.x of nsw-design-system.
The change already exists in master/v1.x (NSWDS v3)
+ Update documentation
+ Replace `branding_version` test with default Public Sans inclusion
+ Add typography settings to  override nsw-design-system
+ editor.css support
> Automatically Apply Public Sans to v2.14.x

- themes/nswds/templates/Includes/MediaHolderChildren.ss
- themes/nswds/templates/NSWDPC/Elemental/Models/Banner/ElementBanner.ss
- themes/nswds/templates/NSWDPC/Elemental/Models/Mediawesome/Includes/ItemList.ss
- themes/nswds/templates/NSWDPC/Waratah/ElementDecoratedContent/Includes/Card.ss
- themes/nswds/templates/NSWDPC/Waratah/ElementDecoratedContent/Includes/ProfileImage.ss
- themes/nswds/templates/NSWDPC/Waratah/ElementalLinks/Includes/Cards.ss
- themes/nswds/templates/NSWDPC/Waratah/ElementalList/Includes/Cards.ss
- themes/nswds/templates/nswds/Includes/Card.ss
- themes/nswds/templates/nswds/Includes/ContentBlock.ss
- themes/nswds/templates/nswds/Includes/ListItem.ss
- themes/nswds/templates/nswds/Includes/Media.ss
I've added the `loading="lazy"` attribute to a number of img elements throughout the theme to help improve the page initial load speed
> add lazy loading to imgs

- themes/nswds/templates/NSWDPC/Waratah/ElementalList/Includes/LinkList.ss
- themes/nswds/templates/nswds/Includes/LinkListItem.ss
In some cases the link was ignored depending on the context.
Handle string links and remove deprecated LinkList_Link handling
> Improve how links are handled in LinkList

- src/Extensions/SiteConfigExtension.php
- themes/nswds/templates/nswds/Includes/Waratah.ss
+ Support custom line breaks on longer agency names - #9
+ Favour "long title" over "Title" if provide, but only in the header component
> NEW: add LongTitle to allow longer title with line break(s)

- themes/nswds/app/frontend/src/scss/components/waratah/_micromodal.scss
- themes/nswds/templates/NSWDPC/Waratah/Includes/Modal.ss
+ On sm viewport, move close button to thumb friendly position
+ remove [x] close action in header
+ Apply positive margin space to align modal elements (https://www.w3.org/TR/css-flexbox-1/#auto-margins)
> Modal mobile viewport improvements

- themes/nswds/app/frontend/src/scss/app.scss
- themes/nswds/app/frontend/src/scss/components/waratah/_grid.scss
- themes/nswds/templates/NSWDPC/Waratah/Includes/ElementHolder.ss
Similar to Bootstrap container-fluid, a fluid container just overrides the max-width on nsw-container and allows the element to take up the full width of the parent element, retaining padding set in nsw-container.
> Add better support for full width containers

- themes/nswds/templates/nswds/Includes/Tags.ss
+ (enh) allow tag list 'size' to be set via include, with default retained as 8
Usage:
```
<% include nswds/Tags Tags_List=$SomeList, Tags_ListSize=32 %>
```
> Allow modification of tag list size

- themes/nswds/templates/NSWDPC/DateInputs/DateCompositeField_holder.ss
The field is a composite field, when it is included in a composite field itself the padding added by the section/container creates a nesting effect.
This was changed back in https://github.com/nswdpc/waratah/commit/59246f4d09a0f58d7412d4bde3e9f37bac8337e6#diff-3bf0e9d733d3bb3ab5509af0a314f0601894b489bbe120eb17037a5799a92321 as part of the form component update.
+ (enh) ensure date input composite field doesn't include extra padding
Not nested in a composite field:
Nested in a composite field:
vs:
> Remove composite field padding in date input

- themes/nswds/templates/SilverStripe/Forms/ReadonlyField.ss
+ (enh) ensure the readonly field is rendered as a block element + avoid inheriting the field's default classes, use some utility classes instead
```php
ReadonlyField::create(
'Sample',
'Suspendisse potenti',
'Duis congue mi in lectus lobortis, ut vestibulum magna varius. Sed facilisis orci at odio dignissim, ut gravida lorem facilisis. Sed nec dapibus tellus. Donec sed ullamcorper metus.'
)->setDescription(
'Nullam fringilla sed ante a tempor. Curabitur lorem ante, imperdiet eget convallis in, tristique nec ligula.'
)->setRightTitle(
'Pellentesque laoreet libero sed tincidunt scelerisque. Sed sapien turpis, pellentesque vel libero ut, mattis luctus magna.'
),
```
Result ...
Possible issues:
+ There is no --border-1 in the DS utility class.
+ Should it try to look like a field at all?
> Readonly field improvements

- themes/nswds/templates/NSWDPC/Members/Includes/ContainerStart.ss
- themes/nswds/templates/NSWDPC/Members/Layout/MemberDirectoryController.ss
- themes/nswds/templates/NSWDPC/Waratah/Includes/PageSearchResults.ss
- themes/nswds/templates/NSWDPC/Waratah/Includes/PageWrapper.ss
- themes/nswds/templates/NSWDPC/Waratah/Pages/Layout/HomePage.ss
- themes/nswds/templates/NSWDPC/Waratah/Security/Includes/MainBody.ss
Fix: the correct id attribute referenced by skipto links is `main-content`
> Fix id attribute referenced by skipto links

- src/Extensions/DesignSystemAssetExtension.php
- src/Traits/FilterFormTrait.php
- themes/nswds/app/frontend/gulpfile.babel.js
- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
- themes/nswds/app/frontend/src/js/components/slimselect.js
- themes/nswds/templates/Dynamic/Elements/Section/Elements/ElementSectionNavigation.ss
- themes/nswds/templates/Includes/MediaHolderChildren.ss
- themes/nswds/templates/Includes/Schema_SpecialAnnouncement.ss
- themes/nswds/templates/Includes/UploaderMeta.ss
- themes/nswds/templates/NSWDPC/Elemental/Models/Mediawesome/Includes/ItemList.ss
- themes/nswds/templates/NSWDPC/Waratah/ElementDecoratedContent/Includes/Card.ss
- themes/nswds/templates/NSWDPC/Waratah/ElementalLinks/Includes/Cards.ss
- themes/nswds/templates/NSWDPC/Waratah/Includes/SVGSprite.ss
- themes/nswds/templates/SilverStripe/Forms/CompositeField_holder.ss
- themes/nswds/templates/SilverStripe/Forms/HTMLReadonlyField_holder.ss
- themes/nswds/templates/SilverStripe/Forms/ListboxField.ss
- themes/nswds/templates/nswds/Includes/Callout.ss
- themes/nswds/templates/nswds/Includes/Card.ss
- themes/nswds/templates/nswds/Includes/FilterForm.ss
- themes/nswds/templates/nswds/Includes/InPageAlert.ss
- themes/nswds/templates/nswds/SVGSprite.ss
+ Update nsw-design-system 3.5.0 -> 3.5.3
+ Update npm requirements (d8d7d765fb95a37d478123c467f0dc189dd5d83c)
+ Remove unused SVG sprite implementation (060b0facea034d276bbb751721897923e6f79f81)
+ select multiple: retain slimselect implementation but do not apply when `<select multiple>` is within a nsw-multi-select parent (931ffadc7ec30a33c393681a78a2d296e4792e63)
+ Fix template issues within FilterForm component (2c65806bba564a3a7827bef55eade6d03d3fc2e7)
+ Update callout, card and in-page-alert templates based on HTML changes in nswds components
Note: the default pagination component shipped remains unchanged, which differs from the change in nsw-design-system v3.5.2. The next/prev buttons do not show on the first/last pages respectively.
> Update to nswds 3.5.3

- themes/nswds/templates/SilverStripe/Forms/CompositeField_holder.ss
- themes/nswds/templates/SilverStripe/Forms/ReadonlyField.ss
- themes/nswds/templates/SilverStripe/Forms/SelectionGroup.ss
nswds 3.6.0 introduced some utility classes to assist styling
+ Update readonly field styling to use utility classes, fixes an issue where the field was outline with the --nsw-brand-accent colour
+ Replace CompositeField background colour with spacing to avoid contrast clashes
+ Update SelectionGroup field holder in line with CompositeField holder change
> Readonly field and Composite Field styling fix and improvement

- themes/nswds/templates/nswds/Includes/Media.ss
In some cases, an empty figcaption element is present. This change allows toggling of caption visibility regardless of the presence of caption,credit or other child elements
> Gallery caption improvements

- src/Services/GalleryFrontend.php
+ Test element existence prior to returning caption value, avoids `undefined` value as caption in certain circumstances
> Fix: test element existence prior to returning caption value

- themes/nswds/app/frontend/src/js/components/slimselect.js
- themes/nswds/app/frontend/src/scss/components/thirdparty/_slimselect.scss
+ Fix: setting name `placeholderText`, not `placeholder`
+ Use data-* attribute values as equivalent settings values (searchPlaceholder, minSelected, maxSelected)
+ Support max/minSelected settings
+ Support searchPlaceholder setting
+ Add a 'matching' dataset property to control how values are matched in the `searchFilter` event
+ Export a function `applySlimSelect` for use elsewhere
+ UI: drop border on delete button
> Slimselect: fixes/improvements

- themes/nswds/templates/SilverStripe/Forms/CompositeField_holder.ss
- themes/nswds/templates/SilverStripe/Forms/HTMLReadonlyField_holder.ss
Maintain spacing consistency in forms.
+ Remove the lg bottom padding from composite field
+ Wrap the HTMLReadonlyField in the form group holder element
> Update HTMLReadonlyField and CompositeField templates

- composer.json
- themes/nswds/app/frontend/package-lock.json
- themes/nswds/app/frontend/package.json
- themes/nswds/app/frontend/src/scss/app.scss
- themes/nswds/app/frontend/src/scss/components/waratah/_date.scss
- themes/nswds/templates/NSWDPC/DateInputs/DateCompositeField_holder.ss
- themes/nswds/templates/NSWDPC/DateInputs/DayOfMonthField_holder.ss
- themes/nswds/templates/NSWDPC/DateInputs/MonthNumberField_holder.ss
- themes/nswds/templates/NSWDPC/DateInputs/TimeField_holder.ss
- themes/nswds/templates/NSWDPC/DateInputs/YearField_holder.ss
- themes/nswds/templates/nswds/Includes/DateInput.ss
See #87 
+ Update nsw-design-system to 3.16.0 to support date inputs component
+ Add templates for nswdpc/silverstripe-datetime-inputs fields with nswds classes
+ Apply override CSS to ensure fields take up container width, for consistency
+ Set version upper boundary  for nswdpc/silverstripe-datetime-inputs requirement
> Update datetime inputs

- docs/en/004_advanced_forms.md
- src/Extensions/FormFieldExtension.php
- themes/nswds/app/frontend/src/scss/components/waratah/_form.scss
- themes/nswds/templates/SilverStripe/Forms/CompositeField_holder.ss
- themes/nswds/templates/SilverStripe/Forms/HTMLReadonlyField_holder.ss
+ Allow arrangement of composite field child fields into equal width, 2, or 3  columns
+ An HTMLReadonlyField is considered a flex break.
+ Update documentation
> Grid composite field

- src/Extensions/PageExtension.php
- themes/nswds/templates/NSWDPC/Waratah/Includes/BackToTop.ss
- themes/nswds/templates/Page.ss
- themes/nswds/templates/nswds/Includes/BackToTop.ss
+ Add 'Back to top' component from nswds. Ref #86
+ Add option in page settings, default off
+ Add form field to settings section
+ Add component template
+ Add include template, can be overridden in themes
The position of the button will interfere with other elements located there (chat bots, captcha badge) but the position can be modified in CSS at a project level, simply:
```css
.nsw-back-to-top {
// etc
left: 1rem;// 50%, 75% etc etc
bottom: 4rem;
}
```
> Add 'Back to top' component

- _config/config.yml
- _config/extensions.yml
- src/Extensions/SiteTreeExtension.php
- themes/nswds/app/static/site.webmanifest.json
- themes/nswds/templates/NSWDPC/Waratah/Includes/Metadata.ss
+ Do not link to a web manifest by default
+ Remove start_url from shipped web manifest
+ Replace manually added meta tags with `{$MetaTags}`
+ Remove unnecessary `X-UA-Compatible` tag
+ Add an extension to conditionally add preview meta tags, when in the relevant preview mode
+ Move viewport to extension
+ Remove generator meta via configuration
> Meta tag updates

- themes/nswds/templates/NSWDPC/Waratah/Includes/AdvancedSearch.ss
- themes/nswds/templates/NSWDPC/Waratah/Includes/GlobalSearch.ss
- themes/nswds/templates/NSWDPC/Waratah/Includes/PageSearchResults.ss
- themes/nswds/templates/NSWDPC/Waratah/Includes/SimpleSearch.ss
- themes/nswds/templates/SilverStripe/CMS/Search/Includes/SearchForm.ss
- themes/nswds/templates/nswds/Includes/Header.ss
+ Provide improved options for custom search forms in projects
+ Decouple search form variants from SilverStripe/CMS/Search/SearchForm
+ Include new templates in SearchForm.ss for BC
+ Replace type="search" with type="text" to avoid visual overlap of search icon and 'x' in header search
> Decouple search forms from CMS search form
